---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSIONS="~> 4.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  required:
    ':development':
      - gem: rspec
        version: '~>3.0'
      - gem: puppetlabs_spec_helper
      - gem: simplecov
      - gem: puppet_facts
      - gem: json
      - gem: mocha
        version: '~>0.10.5'
    ':system_tests':
      - gem: beaker-rspec
      - gem: serverspec
appveyor.yml:
  matrix:
    - PUPPET_GEM_VERSION: 3.7.5
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: 3.7.5
      RUBY_VER: 200-x64
    - PUPPET_GEM_VERSION: 3.8.1
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: 3.8.1
      RUBY_VER: 200-x64
    - PUPPET_GEM_VERSION: 4.0.0
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: 4.0.0
      RUBY_VER: 21-x64
  test_script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
