---
:global:
  supported_oss:
    puppetlabs-acl:                      [windows]
    puppetlabs-chocolatey:               [windows]
    puppetlabs-dism:                     [windows]
    puppetlabs-dsc:                      [windows]
    puppetlabs-iis:                      [windows]
    puppetlabs-powershell:               [windows]
    puppetlabs-reboot:                   [windows]
    puppetlabs-registry:                 [windows]
    puppetlabs-sqlserver:                [windows]
    puppetlabs-wsus_client:              [windows]
    puppetlabs-inifile:                  [linux,windows]
    puppetlabs-stdlib:                   [linux,windows]
    puppetlabs-accounts:                 [linux]
    puppetlabs-apache:                   [linux]
    puppetlabs-apt:                      [linux]
    puppetlabs-concat:                   [linux,windows]
    puppetlabs-firewall:                 [linux]
    puppetlabs-haproxy:                  [linux]
    puppetlabs-hocon:                    [linux]
    puppetlabs-ibm_installation_manager: [linux]
    puppetlabs-inifile:                  [linux]
    puppetlabs-java:                     [linux]
    puppetlabs-java_ks:                  [linux]
    puppetlabs-mongodb:                  [linux]
    puppetlabs-motd:                     [linux]
    puppetlabs-mysql:                    [linux]
    puppetlabs-ntp:                      [linux]
    puppetlabs-postgresql:               [linux]
    puppetlabs-puppet_agent:             [linux,windows]
    puppetlabs-rabbitmq:                 [linux]
    puppetlabs-stdlib:                   [linux]
    puppetlabs-tagmail:                  [linux]
    puppetlabs-tftp:                     [linux]
    puppetlabs-tomcat:                   [linux]
    puppetlabs-vcsrepo:                  [linux]
    puppetlabs-vsphere:                  [linux]
    puppetlabs-xinetd:                   [linux]

.gitattributes:
  include:
    '*.rb': 'eol=lf'
    '*.erb': 'eol=lf'
    '*.pp': 'eol=lf'
    '*.sh': 'eol=lf'
.travis.yml:
  script: "\"bundle exec rake release_checks\""
  docker_sets:
  - set: docker/ubuntu-14.04
  - set: docker/centos-7
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
    rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=@@SET@@
    script: bundle exec rake beaker
  includes:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
    bundler_args: --without system_tests
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0"
    bundler_args: --without system_tests
Gemfile:
  required:
    ':development':
      - gem: puppet-lint
      # Only non-windows because it needs json
      - gem: metadata-json-lint
        platforms: 'ruby'
      - gem: puppet_facts
      # newer version required for ruby 1.9 compat
      - gem: puppet-blacksmith
        version: '>= 3.4.0'
        platforms: 'ruby'
      - gem: puppetlabs_spec_helper
        version: '>= 1.2.1'
      # newer version required to PUP-5743
      - gem: rspec-puppet
        version: '>= 2.3.2'
      # Only non-windows because it needs json
      - gem: rspec-puppet-facts
        platforms: 'ruby'
      # the newly released mocha 1.2.0 causes hangs during spec testing. See MODULES-3958 for a long-term solution
      - gem: mocha
        version: '< 1.2.0'
      # Only non-windows because it needs json
      - gem: simplecov
        platforms: 'ruby'
      - gem: parallel_tests
        version: '< 2.10.0'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')"
      - gem: parallel_tests
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.0.0')"
      - gem: rubocop
        version: '0.41.2'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')"
      - gem: rubocop
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.0.0')"
      - gem: rubocop-rspec
        version: '~> 1.6'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
      - gem: pry
      # json_pure 2.0.2 added a requirement on ruby >= 2. We pin to json_pure <= 2.0.1
      # if using ruby 1.x
      - gem: json_pure
        version: '<= 2.0.1'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')"
      - gem: fast_gettext
        version: '1.1.0'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.1.0')"
      - gem: fast_gettext
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.1.0')"
      # We don't want native extensions from rainbow
      - gem: rainbow
        version: '< 2.2.0'
    ':system_tests':
      - gem: beaker
        version: '>= 3'
        from_env: 'BEAKER_VERSION'
      # beaker 3 requires this for PE installs
      - gem: beaker-pe
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
      - gem: master_manipulator
      - gem: beaker-hostgenerator
        from_env: 'BEAKER_HOSTGENERATOR_VERSION'
      - gem: beaker-abs
        from_env: 'BEAKER_ABS_VERSION'
        version: '~> 0.1'
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests"
  matrix:
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23-x64
    # Oldest supported version
    - PUPPET_GEM_VERSION: '4.2.3'
      RUBY_VER: 21-x64
  test_script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"

LICENSE:
  license_type: 'apache2' # Available options 'puppetpe' and 'apache2' (default is apache2)

MAINTAINERS.md:
  maintainers:
    - "Puppet Forge Modules Team `forge-modules |at| puppet |dot| com`"

# Apache 2 NOTICE file generation.  Please mark unmanaged:true if using puppetpe license type
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 'latest'
    # - name: '<name of holder>' (required)
    #   begin: <year or 'latest'> (optional) (latest is the year when modsync is run)
    #   end:   <year or 'latest'> (optional) (latest is the year when modsync is run)

Rakefile:
  default_disabled_lint_checks:
  - 'relative'

spec/spec.opts:
  delete: true

locales/config.yaml:
  copyright_holder: 'Puppet, Inc.'
  comments_tag: 'TRANSLATOR'
  bugs_address: 'docs@puppet.com'
  default_locale: 'en'
  source_files: ['metadata.json']
