---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  supports_windows:
    - puppetlabs-acl
    - puppetlabs-chocolatey
    - puppetlabs-dism
    - puppetlabs-dsc
    - puppetlabs-powershell
    - puppetlabs-reboot
    - puppetlabs-registry
    - puppetlabs-sqlserver
    - puppetlabs-wsus_client
  required:
    ':development':
      - gem: puppet-lint
      - gem: metadata-json-lint
      - gem: puppet_facts
      # newer version required for ruby 1.9 compat
      - gem: puppet-blacksmith
        version: '>= 3.4.0'
        platforms: 'ruby'
      - gem: puppetlabs_spec_helper
        version: '>= 1.2.1'
      # newer version required to PUP-5743
      - gem: rspec-puppet
        version: '>= 2.3.2'
      - gem: rspec-puppet-facts
      # the newly released mocha 1.2.0 causes hangs during spec testing. See MODULES-3958 for a long-term solution
      - gem: mocha
        version: '< 1.2.0'
      - gem: simplecov
      - gem: parallel_tests
        version: '< 2.10.0'
        condition: "Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.0.0')"
      - gem: parallel_tests
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.0.0')"
      - gem: rubocop
        version: '0.41.2'
        condition: "Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.0.0')"
      - gem: rubocop
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.0.0')"
      - gem: rubocop-rspec
        version: '~> 1.6'
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0')"
      - gem: pry
      # json_pure 2.0.2 added a requirement on ruby >= 2. We pin to json_pure <= 2.0.1
      # if using ruby 1.x
      - gem: json_pure
        version: '<= 2.0.1'
        condition: "Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.0.0')"
      - gem: json_pure
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.0.0')"
    ':system_tests':
      - gem: beaker
        from_env: 'BEAKER_VERSION'
        version: '~> 2.20'
        condition: "supports_windows"
      - gem: beaker
        from_env: 'BEAKER_VERSION'
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0') and ! supports_windows"
      - gem: beaker
        from_env: 'BEAKER_VERSION'
        version: '< 3'
        condition: "Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.3.0') and ! supports_windows"
      # beaker 3 requires this for PE installs
      - gem: beaker-pe
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0')"
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
        # newer version required to avoid BKR-537
        version: '>= 3.4'
        condition: "! supports_windows"
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
        # newer version required to avoid BKR-537
        version: '~> 5.1'
        condition: "supports_windows"
      - gem: beaker-puppet_install_helper
      - gem: master_manipulator
      - gem: beaker-hostgenerator
        from_env: 'BEAKER_HOSTGENERATOR_VERSION'
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests"
  matrix:
    - PUPPET_GEM_VERSION: '~> 3.0'
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: '~> 3.0'
      RUBY_VER: 200-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 23-x64
  test_script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"

LICENSE:
  license_type: 'apache2' # Available options 'puppetpe' and 'apache2' (default is apache2)

MAINTAINERS.md:
  maintainers:
    - "Puppet Forge Modules Team `forge-modules |at| puppet |dot| com`"

# Apache 2 NOTICE file generation.  Please mark unmanaged:true if using puppetpe license type
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 'latest'
    # - name: '<name of holder>' (required)
    #   begin: <year or 'latest'> (optional) (latest is the year when modsync is run)
    #   end:   <year or 'latest'> (optional) (latest is the year when modsync is run)    

Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
