---
:global:
  supported_oss:
    puppetlabs-acl:                          [windows]
    puppetlabs-chocolatey:                   [windows]
    puppetlabs-dism:                         [windows]
    puppetlabs-dsc:                          [windows]
    puppetlabs-dsc_lite:                     [windows]
    puppetlabs-iis:                          [windows]
    puppetlabs-powershell:                   [windows]
    puppetlabs-reboot:                       [windows]
    puppetlabs-registry:                     [windows]
    puppetlabs-scheduled_task:               [windows]
    puppetlabs-sqlserver:                    [windows]
    puppetlabs-wsus_client:                  [windows]
    puppetlabs-inifile:                      [linux,windows]
    puppetlabs-stdlib:                       [linux,windows]
    puppetlabs-accounts:                     [linux]
    puppetlabs-apache:                       [linux]
    puppetlabs-apt:                          [linux]
    puppetlabs-concat:                       [linux,windows]
    puppetlabs-firewall:                     [linux]
    puppetlabs-haproxy:                      [linux]
    puppetlabs-hocon:                        [linux]
    puppetlabs-ibm_installation_manager:     [linux]
    puppetlabs-inifile:                      [linux]
    puppetlabs-java:                         [linux]
    puppetlabs-java_ks:                      [linux,windows]
    puppetlabs-mysql:                        [linux]
    puppetlabs-ntp:                          [linux]
    puppetlabs-netscaler:                    [linux]
    puppetlabs-postgresql:                   [linux]
    puppetlabs-puppet_agent:                 [linux,windows]
    puppetlabs-satellite_pe_tools:           [linux]
    puppetlabs-stdlib:                       [linux]
    puppetlabs-tagmail:                      [linux]
    puppetlabs-tftp:                         [linux]
    puppetlabs-tomcat:                       [linux]
    puppetlabs-translate:                    [linux]
    puppetlabs-vcsrepo:                      [linux]
    puppetlabs-vsphere:                      [linux]
    puppetlabs-websphere_application_server: [linux]
    puppetlabs-windows:                      [windows]
    puppetlabs-xinetd:                       [linux]
    yang_ietf:                               [linux]

.gitattributes:
  include:
    '*.rb': 'eol=lf'
    '*.erb': 'eol=lf'
    '*.pp': 'eol=lf'
    '*.sh': 'eol=lf'
.travis.yml:
  script: "\"bundle exec rake release_checks\""
  docker_sets:
  - set: docker/ubuntu-14.04
  - set: docker/centos-7
  docker_defaults:
    # values will replace @@SET@@ with the docker_sets' value
    rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=@@SET@@
    script: bundle exec rake beaker
  includes:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0"
    bundler_args: --without system_tests
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
    bundler_args: --without system_tests
Gemfile:
  required:
    ':development':
      # Gems built using puppet-module-gems utility
      - gem: 'puppet-module-posix-default-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-default-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
      - gem: 'puppet-module-posix-dev-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-dev-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
        version: '0.0.7'
      # json_pure 2.0.2 added a requirement on ruby >= 2. We pin to json_pure <= 2.0.1
      # if using ruby 1.x
      - gem: json_pure
        version: '<= 2.0.1'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')"
      - gem: fast_gettext
        version: '1.1.0'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.1.0')"
      - gem: fast_gettext
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.1.0')"
    ':system_tests':
      # Gems built using puppet-module-gems utility
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: 'ruby'
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - 'mswin'
          - 'mingw'
          - 'x64_mingw'
      - gem: beaker
        version: '>= 3'
        from_env: 'BEAKER_VERSION'
      # beaker 3 requires this for PE installs
      - gem: beaker-pe
      - gem: beaker-rspec
        from_env: 'BEAKER_RSPEC_VERSION'
      - gem: beaker-hostgenerator
        from_env: 'BEAKER_HOSTGENERATOR_VERSION'
      - gem: beaker-abs
        from_env: 'BEAKER_ABS_VERSION'
        version: '~> 0.1'
      - gem: puppet-blacksmith
        version: '~> 3.4'
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests"
  matrix:
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
    - PUPPET_GEM_VERSION: '~> 5.0'
      RUBY_VER: 24
    - PUPPET_GEM_VERSION: '~> 5.0'
      RUBY_VER: 24-x64
    # Oldest supported version
    - PUPPET_GEM_VERSION: '4.7.1'
      RUBY_VER: 21-x64
  test_script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"

LICENSE:
  license_type: 'apache2' # Available options 'puppetpe' and 'apache2' (default is apache2)

MAINTAINERS.md:
  maintainers:
    - "Puppet Forge Modules Team `forge-modules |at| puppet |dot| com`"

# Apache 2 NOTICE file generation.  Please mark unmanaged:true if using puppetpe license type
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 'latest'
    # - name: '<name of holder>' (required)
    #   begin: <year or 'latest'> (optional) (latest is the year when modsync is run)
    #   end:   <year or 'latest'> (optional) (latest is the year when modsync is run)

Rakefile:
  default_disabled_lint_checks:
  - 'relative'

CONTRIBUTING.md:

spec/spec.opts:
  delete: true

locales/config.yaml:
  copyright_holder: 'Puppet, Inc.'
  comments_tag: 'TRANSLATOR'
  bugs_address: 'docs@puppet.com'
  default_locale: 'en'
  source_files:
    - './lib/**/*.rb'

spec/spec_helper.rb:
spec/acceptance/nodesets/centos-7-x64.yml:
spec/acceptance/nodesets/debian-8-x64.yml:
spec/acceptance/nodesets/default.yml:
spec/acceptance/nodesets/docker/centos-7.yml:
spec/acceptance/nodesets/docker/debian-8.yml:
spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
