---
.travis.yml:
  script: "\"bundle exec rake validate lint spec\""
  includes:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: json
      - gem: metadata-json-lint
      - gem: puppet_facts
      - gem: puppet-blacksmith
      - gem: puppetlabs_spec_helper
      # newer version required to PUP-5743
      - gem: rspec-puppet
        version: '>= 2.3.2'
      - gem: simplecov
    ':system_tests':
      - gem: beaker-rspec
      # newer version required to avoid BKR-537
        version: '>= 3.4'
      - gem: beaker
        version: '*location_for(ENV["BEAKER_VERSION"])'
      - gem: serverspec
      - gem: beaker-puppet_install_helper
      - gem: master_manipulator
      - gem: beaker-hostgenerator
        version: '*location_for(ENV["BEAKER_HOSTGENERATOR_VERSION"])'
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
